### ISSUE TITLE
Issuance before Deck is confirmed

### ISSUE THREAD

**Issue by saeveritt** [PeerAssets/pacli#7]
Give users a proper warning when trying to issue cards for a deck with 0 confirmations

**Comment by hrobeers** [comment]
It' shouldn't give an error IMO.
It may give a warning.

**Comment by saeveritt** [comment]
Agreed and modified the issue.

**Comment by peerchemist** [comment]
Solved with: https://github.com/PeerAssets/pacli/commit/66f7756a0b6756f3149dbed548271b88189bde35
